add shawn suggestions
alvarj84/dsny-sysdig-values pull request #1
Opened 2023-03-10 22:08 UTC by alvarj84

This is a PR in order to keep track of the changes in the values file used by customer DSNY.

2023-03-10 22:24 UTC, shawnjohnson commented on sysdig-values.yaml
> +  #   tag: 12.3.1
```suggestion
```
We can remove the yaml for image/tag completely. No need to leave the commented out lines. Ideally in 99% of use-cases the customer should allow these values to be driven by the chart default values.

2023-03-10 22:25 UTC, shawnjohnson requested changes

2023-03-10 22:25 UTC, shawnjohnson commented on sysdig-values.yaml
> +    #     tag: 1.15.0
```suggestion
```

2023-03-10 22:25 UTC, shawnjohnson commented on sysdig-values.yaml
> +      #   tag: 1.4.4
```suggestion
```

2023-03-10 22:25 UTC, shawnjohnson commented on sysdig-values.yaml
> +      #   tag: 0.3.4
```suggestion
```

2023-03-10 22:25 UTC, shawnjohnson commented on sysdig-values.yaml
> +      #   tag: 0.1.22
```suggestion
```

2023-03-10 22:25 UTC, shawnjohnson commented on sysdig-values.yaml
> +      #   tag: 0.1.14
```suggestion
```

2023-03-13 15:05 UTC, alvarj84 commented
Thanks @shawnjohnson I added your suggestions.

2023-03-13 15:05 UTC, merged